---
# Per environment values which override defaults in hmpps-jobs-board-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: jobs-board-preprod.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: preprod
    ENVIRONMENT_NAME: 'PRE-PRODUCTION'
    S3_REGION: eu-west-2
    INGRESS_URL: "https://jobs-board-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    JOB_API_URL: "https://jobs-board-api-preprod.hmpps.service.justice.gov.uk"
    WORK_AFTER_RELEASE_URL: "https://get-ready-for-work-preprod.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: PREPROD
    FILTER_JOBS_CREATED_BY_ME_ENABLED: false

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: education-alerts-non-prod
