---
# Per environment values which override defaults in hmpps-jobs-board-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: jobs-board-dev.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT_NAME: DEV
    ENVIRONMENT_NAME: 'DEV'
    S3_REGION: eu-west-2
    INGRESS_URL: "https://jobs-board-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"
    JOB_API_URL: "https://support-dev.hmpps.service.justice.gov.uk/feedback-and-support"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: DEV


generic-prometheus-alerts:
  alertSeverity: prison-education-alerts