---
# Per environment values which override defaults in hmpps-jobs-board-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: jobs-board-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://jobs-board-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: prison-education-alerts