---
# Per environment values which override defaults in hmpps-jobs-board-ui/values.yaml

generic-service:
  serviceAccountName: education-skills-and-work-devs-development
  replicaCount: 2

  ingress:
    host: jobs-board-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    ENVIRONMENT: DEV
    ENVIRONMENT_NAME: 'DEV'
    S3_REGION: eu-west-2
    INGRESS_URL: "https://jobs-board-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"
    JOB_API_URL: "https://jobs-board-api-dev.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    WORK_AFTER_RELEASE_URL: "https://get-ready-for-work-dev.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: DEV
    AUDIT_ENABLED: 'true'

  namespace_secrets:
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: education-alerts-non-prod